// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "trftipogeneral"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.MaestroBusiness;
using Mozo.Model.Maestro;
using Mozo.Model.Seguridad;

namespace Mozo.Api.Maestro;
///<summary>
/// Endpoints para gestión de TipoGeneral
///</summary>
///<history>
/// Create by Jonatan Abregu
///</history>
public static partial class TipoGeneralEndPoints
{
    /// <summary>
    /// Mapea todas las rutas de TipoGeneral
    /// </summary>
    public static RouteGroupBuilder MapTipoGeneral(this RouteGroupBuilder g)
    {
        g.WithSecurity();

        g.MapGet("/byid", SelByIdAsync)
          .WithResponses<TipoGeneralModel>(StatusCodes.Status200OK)
         .Produces(StatusCodes.Status404NotFound)
         .WithDescription("Obtener una Tipo General");

        g.MapGet("/active", SelAllActiveAsync)
          .WithResponses<IEnumerable<TipoGeneralModel>>(StatusCodes.Status200OK)
          .Produces(StatusCodes.Status404NotFound)
          .WithDescription("Obtener todos los Tipo General activos");

        g.MapGet("/modulos/active", SelAllActiveByModuloAsync)
          .WithResponses<IEnumerable<TipoGeneralModel>>(StatusCodes.Status200OK)
          .Produces(StatusCodes.Status404NotFound)
          .WithDescription("Obtener todos los Tipo General activos del Módulo");

        return g;
    }

}
public static partial class TipoGeneralEndPoints
{

    private static async Task<IResult>
        SelByIdAsync(
      [AsParameters]  TipoGeneralFilterDto f,
        ITipoGeneralBusiness ITipoGeneral)
    {
        TipoGeneralModel? i = await ITipoGeneral.SelByIdAsync(f);
        if (i == null)
            return Results.NotFound();
        return Results.Ok(i);
    }
    private static async Task<IResult> 
        SelAllActiveAsync(
       [AsParameters] TipoGeneralFilterDto f,
        ITipoGeneralBusiness ITipoGeneral)
    {

        IEnumerable<TipoGeneralModel> r = await ITipoGeneral.SelAllActiveAsync(f);
        return Results.Ok(r.OrderBy(x => x.NuOrden));
    }

    private static async Task<IResult> 
        SelAllActiveByModuloAsync(
        [AsParameters] TipoGeneralFilterDto f,
        ITipoGeneralBusiness ITipoGeneral)
    {
        IEnumerable<TipoGeneralModel> r = await ITipoGeneral.SelAllActiveByModuloAsync(f);
        return Results.Ok(r.OrderBy(x => x.NuOrden));
    }

}

